name: Run Jobs on PR
on: pull_request

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: jpmcb/prow-github-actions@main
        with:
          jobs: lgtm
          github-token: '${{ secrets.GITHUB_TOKEN }}'